### ISSUE TITLE
sonos feedback or polling

### ISSUE THREAD

**Issue by CreasaBE** [bitfocus/companion-module-sonos-speakers#1] opened 2020-06-19 05:31 UTC
Hi,

Is there a possibility to add the feedback from Sonos to a button please? 
For example, I have setup a play/pause button and some volume buttons, but it would be nice if the play/pause was also updated regularly. When I pause the playback through the sonos app, the button in the compagnon app and streamdeck stays in it's position where it was. When it was in play mode it'll stay in play mode regardless if I pause playback through the app.

Just a suggestion and I don't know how much work that'll give you. It's been done for Openhab etc so it is possible, but I don't know how much work that will be and if you'd be willing to incorporate that.

Thanks in advance.

**Comment by svrooij** [comment] 2020-12-08 10:22
This should be perfectly doable, since the used sonos library (mine) already [supports events](https://svrooij.io/node-sonos-ts/sonos-device/events.html). You can just do:

```js
sonosDevice.Events.on('volume', (newVolume) => {
  // Do something with newVolume (change the button text)
}
```

**Comment by Julusian** [comment] 2020-12-08 10:58
Feedback from sonos already works via events https://github.com/bitfocus/companion-module-sonos-speakers/blob/master/src/index.ts#L117
It generally works, but I have found it to not occasionally.

eg, sometimes when I change the volume via companion the variable doesnt update for 4 or 5 presses. 
I havent spent any time looking into where the problem is here, and I don't use this myself anymore so don't know when I will be able to look into this issue further.

**Comment by svrooij** [comment] 2020-12-08 11:10
If you already use events, then it might be an issue off the library not being able to renew the event subscription with the speaker. This is fixed in the next release of the library.

**Comment by Julusian** [comment] 2020-12-08 11:14
Well we are using v1.2.3 of your library, so I would not be surprised if this was fixed by updating it to something more recent :)

**Comment by Julusian** [comment] 2023-12-16 16:14
I've just checked and this is already supported and still working

**Closed as completed by Julusian** 2023-12-16 16:14 UTC
